apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pushwf  
  labels: 
    name: "pushwf"
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 30s"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pushwf
  template:
    metadata:
      name: pushwf
      labels:
        app: pushwf
    spec:     
      containers:                    
        - image: vishwakarmaniraj/keel-prac:latest
          imagePullPolicy: Always # this is required to force pull image     
          name: pushwf
          ports:
            - containerPort: 8500
              #livenessProbe:
              # httpGet:
              #path: /
              #port: 8500
              #initialDelaySeconds: 10
              #timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pushwf
spec:
  selector:
    app: pushwf
  ports:
    - port: 8500
      targetPort: 8500
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pushwf
spec:
  rules:
  - host: keel-prac.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: pushwf
          servicePort: 8500
